// Compose rendering + port semantics (F15 control-plane isolation, F26 explicit vs dynamic host ports).

import path from 'node:path';
import type { ShipSpec } from '../shared/types.js';
import { writeFileAtomic } from './atomic.js';

const q = (s: string) => JSON.stringify(s);

/** empty file pinned via --env-file: app secrets must NOT control compose interpolation/project name (F15) */
export const COMPOSE_ENV_FILE = 'compose.env';
/** service env file name — deliberately not `.env` so compose never treats it as the control plane */
export const RUNTIME_ENV_FILE = 'runtime.env';

export function renderComposeFile(app: string, imageRef: string, spec: ShipSpec, withEnvFile: boolean): string {
  const lines: string[] = [
    '# generated by ship-agent — manual edits will be overwritten',
    'services:',
    `  ${app}:`,
    `    image: ${q(imageRef)}`,
    '    restart: unless-stopped',
  ];
  if (spec.ports?.length) {
    lines.push('    ports:');
    for (const p of spec.ports) lines.push(`      - ${q(p)}`);
  }
  if (withEnvFile) {
    lines.push('    env_file:', `      - ${q(RUNTIME_ENV_FILE)}`);
  }
  return `${lines.join('\n')}\n`;
}

export async function writeComposeFile(appDir: string, content: string): Promise<void> {
  await writeFileAtomic(path.join(appDir, 'compose.yaml'), content);
}

/** host port explicitly pinned by the operator (healthcheck.hostPort or 'HOST:CONTAINER'); undefined when only dynamic (F26) */
export function explicitHostPort(spec: ShipSpec): number | undefined {
  if (spec.healthcheck?.hostPort) return spec.healthcheck.hostPort;
  const first = spec.ports?.[0];
  if (!first || !first.includes(':')) return undefined;
  const n = Number(first.split(':')[0]);
  return n >= 1 && n <= 65535 ? n : undefined;
}

/** container port of the first declared port — used to query the actual dynamic mapping */
export function firstContainerPort(spec: ShipSpec): number | undefined {
  const first = spec.ports?.[0];
  if (!first) return undefined;
  const c = first.includes(':') ? first.split(':')[1] : first;
  const n = Number(c);
  return n >= 1 && n <= 65535 ? n : undefined;
}
