import React from 'react';
import { cn, useI18n } from '@svton/ui';
import type { ISettingsAdapter } from '../settings-adapter.types';
import { Badge, Card, INPUT_CLS } from '../settings-ui';
import { useMarketplaceSection } from './use-marketplace-section';

export function MarketplaceSection({ adapter, onReload }: {
  adapter: ISettingsAdapter; onReload: () => void;
}) {
  const { formatNumber, translate: t } = useI18n();
  const model = useMarketplaceSection(adapter, onReload);
  return <div>
    <div className="mb-6"><h2 className="text-lg text-white font-medium">{t('settings.marketplace.title')}</h2><p className="text-xs text-gray-500 mt-0.5">{t('settings.marketplace.description')}</p></div>
    <div className="mb-4 flex min-w-0 flex-col gap-2 sm:flex-row sm:items-center">
      <div className="flex min-w-0 flex-1 flex-col gap-2 sm:flex-row"><label className="min-w-0 flex-1"><span className="sr-only">{t('settings.marketplace.search')}</span><input type="text" value={model.searchQuery} onChange={(event) => model.setSearchQuery(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && model.search()} placeholder={t('settings.marketplace.placeholder')} className={cn(INPUT_CLS, 'min-w-0 flex-1')} /></label><button onClick={model.search} disabled={model.loading} className="min-h-11 shrink-0 rounded-lg bg-cyan-600 px-3 text-[11px] font-medium text-white disabled:opacity-50">{t('action.search')}</button></div>
      <div role="group" aria-label={t('settings.marketplace.sort')} className="flex items-center rounded-lg bg-[#171717] p-0.5">{(['trending', 'all-time', 'hot'] as const).map((view) => <button key={view} aria-pressed={model.viewMode === view && !model.searchQuery} onClick={() => model.changeView(view)} className={cn('min-h-11 flex-1 rounded-md px-2.5 text-[10px] sm:flex-none', model.viewMode === view && !model.searchQuery ? 'bg-[#2a2a2a] text-white' : 'text-gray-500 hover:text-gray-300')}>{t(view === 'trending' ? 'settings.marketplace.trending' : view === 'all-time' ? 'settings.marketplace.allTime' : 'settings.marketplace.hot')}</button>)}</div>
    </div>
    {model.installStatus && <div role={model.installStatus.kind === 'error' ? 'alert' : 'status'} className={cn('text-[11px] px-3 py-2 rounded-lg mb-3', model.installStatus.kind === 'success' ? 'text-green-400 bg-green-900/20' : 'text-red-400 bg-red-900/20')}>{model.installStatus.message}</div>}
    {model.error && <div role="alert" className="text-[11px] px-3 py-2 rounded-lg mb-3 text-red-400 bg-red-900/20">{model.error}</div>}
    {model.loading ? <Card><div className="text-center py-8 text-gray-600 text-sm">{t('settings.marketplace.loading')}</div></Card> : model.skills.length === 0 ? <Card><div className="text-center py-8 text-gray-600 text-sm">{t('settings.marketplace.empty')}</div></Card> : <div className="space-y-2">{model.skills.map((skill) => <Card key={skill.id} className="flex min-w-0 flex-wrap items-center gap-3 !px-4 !py-3 sm:flex-nowrap"><div className="flex-1 min-w-0"><div className="flex items-center gap-2 mb-0.5"><span className="text-sm text-gray-200 font-medium truncate">{skill.name}</span>{skill.installed && <Badge color="green">{t('settings.marketplace.installed')}</Badge>}</div><div className="text-[11px] text-gray-500 truncate">{skill.source} · {t(skill.installs === 1 ? 'settings.marketplace.installCountOne' : 'settings.marketplace.installCount', { count: formatNumber(skill.installs) })}</div></div><button onClick={() => skill.installed ? undefined : void model.install(skill.id)} disabled={model.installingId === skill.id || skill.installed} className={cn('min-h-11 shrink-0 rounded-lg px-3 text-[11px] font-medium whitespace-nowrap', skill.installed ? 'bg-[#222] text-gray-600 cursor-default' : 'bg-cyan-600 text-white hover:bg-cyan-500 disabled:opacity-50')}>{t(model.installingId === skill.id ? 'settings.marketplace.installing' : skill.installed ? 'settings.marketplace.installed' : 'settings.marketplace.install')}</button></Card>)}</div>}
    {!model.searchQuery && model.total > 20 && <div className="flex items-center justify-center gap-2 mt-4"><button onClick={() => model.changePage(model.page - 1)} disabled={model.page === 0 || model.loading} className="min-h-11 rounded-lg border border-[#333] px-3 text-[11px] text-gray-400 hover:text-white disabled:opacity-30">{t('settings.marketplace.previous')}</button><span className="text-[11px] text-gray-600">{t('settings.marketplace.page', { page: model.page + 1, total: Math.ceil(model.total / 20) })}</span><button onClick={() => model.changePage(model.page + 1)} disabled={(model.page + 1) * 20 >= model.total || model.loading} className="min-h-11 rounded-lg border border-[#333] px-3 text-[11px] text-gray-400 hover:text-white disabled:opacity-30">{t('settings.marketplace.next')}</button></div>}
  </div>;
}
