export const releaseStagingDeploymentSelect = {
  id: true,
  environmentId: true,
  artifactManifestId: true,
  status: true,
  targetType: true,
  executorKey: true,
  adapterKey: true,
  dryRun: true,
  branch: true,
  commitSha: true,
  params: true,
  commandPlan: true,
  logs: true,
  result: true,
  error: true,
  startedAt: true,
  finishedAt: true,
  createdAt: true,
} as const;
