import { Injectable } from '@nestjs/common';
import { CDNConfigDto, CDNProvider, CDNRefreshDto } from './dto/cdn.dto';

@Injectable()
export class CDNService {
  // 生成 CDN 资源 URL 前缀配置
  generateCDNUrlConfig(config: CDNConfigDto): Record<string, string> {
    const protocol = config.enableHttps ? 'https' : 'http';
    const baseUrl = `${protocol}://${config.domain}`;

    return {
      CDN_BASE_URL: baseUrl,
      CDN_STATIC_URL: `${baseUrl}/static`,
      CDN_ASSETS_URL: `${baseUrl}/assets`,
      CDN_UPLOAD_URL: `${baseUrl}/uploads`,
    };
  }

  // 生成前端 CDN 配置代码
  generateFrontendConfig(config: CDNConfigDto): string {
    const protocol = config.enableHttps ? 'https' : 'http';
    const baseUrl = `${protocol}://${config.domain}`;

    return `// CDN Configuration
// Generated by svton initializer

export const CDN_CONFIG = {
  baseUrl: '${baseUrl}',
  staticUrl: '${baseUrl}/static',
  assetsUrl: '${baseUrl}/assets',
  uploadUrl: '${baseUrl}/uploads',
  
  // Helper function to get CDN URL
  getUrl: (path: string) => {
    if (path.startsWith('http')) return path;
    return \`${baseUrl}\${path.startsWith('/') ? path : '/' + path}\`;
  },
  
  // Helper for image URLs with resize
  getImageUrl: (path: string, width?: number, height?: number) => {
    const base = CDN_CONFIG.getUrl(path);
    if (!width && !height) return base;
    const params = new URLSearchParams();
    if (width) params.set('w', String(width));
    if (height) params.set('h', String(height));
    return \`\${base}?\${params.toString()}\`;
  },
};

export default CDN_CONFIG;
`;
  }

  // 生成 CDN 刷新脚本
  generateRefreshScript(config: CDNConfigDto): string {
    const scripts: Record<CDNProvider, string> = {
      [CDNProvider.QINIU]: this.generateQiniuRefreshScript(config),
      [CDNProvider.ALIYUN]: this.generateAliyunRefreshScript(config),
      [CDNProvider.TENCENT]: this.generateTencentRefreshScript(config),
      [CDNProvider.CLOUDFLARE]: this.generateCloudflareRefreshScript(config),
    };

    return scripts[config.provider];
  }

  private generateQiniuRefreshScript(config: CDNConfigDto): string {
    return `#!/bin/bash
# Qiniu CDN Refresh Script for ${config.domain}
# Requires: qshell (https://developer.qiniu.com/kodo/tools/1302/qshell)

# Configuration
DOMAIN="${config.domain}"
ACCESS_KEY="\${QINIU_ACCESS_KEY}"
SECRET_KEY="\${QINIU_SECRET_KEY}"

# Refresh URLs
refresh_urls() {
    local urls=("$@")
    for url in "\${urls[@]}"; do
        echo "Refreshing: $url"
        qshell cdnrefresh -ak "$ACCESS_KEY" -sk "$SECRET_KEY" "$url"
    done
}

# Refresh directories
refresh_dirs() {
    local dirs=("$@")
    for dir in "\${dirs[@]}"; do
        echo "Refreshing directory: $dir"
        qshell cdnrefresh -ak "$ACCESS_KEY" -sk "$SECRET_KEY" --dirs "$dir"
    done
}

# Usage examples:
# refresh_urls "https://${config.domain}/index.html" "https://${config.domain}/app.js"
# refresh_dirs "https://${config.domain}/static/"

echo "Qiniu CDN refresh script ready"
`;
  }

  private generateAliyunRefreshScript(config: CDNConfigDto): string {
    return `#!/bin/bash
# Aliyun CDN Refresh Script for ${config.domain}
# Requires: aliyun-cli

# Configuration
DOMAIN="${config.domain}"

# Refresh URLs
aliyun cdn RefreshObjectCaches \\
    --ObjectPath "https://${config.domain}/" \\
    --ObjectType File

echo "Aliyun CDN refresh completed"
`;
  }

  private generateTencentRefreshScript(config: CDNConfigDto): string {
    return `#!/bin/bash
# Tencent CDN Refresh Script for ${config.domain}
# Requires: tccli

# Configuration
DOMAIN="${config.domain}"

# Refresh URLs
tccli cdn PurgeUrlsCache \\
    --Urls '["https://${config.domain}/"]'

echo "Tencent CDN refresh completed"
`;
  }

  private generateCloudflareRefreshScript(config: CDNConfigDto): string {
    return `#!/bin/bash
# Cloudflare CDN Refresh Script for ${config.domain}
# Requires: CLOUDFLARE_API_TOKEN and CLOUDFLARE_ZONE_ID

# Configuration
ZONE_ID="\${CLOUDFLARE_ZONE_ID}"
API_TOKEN="\${CLOUDFLARE_API_TOKEN}"

# Purge everything
curl -X POST "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/purge_cache" \\
    -H "Authorization: Bearer $API_TOKEN" \\
    -H "Content-Type: application/json" \\
    --data '{"purge_everything":true}'

echo "Cloudflare CDN purge completed"
`;
  }

  // 生成 Next.js CDN 配置
  generateNextJSConfig(config: CDNConfigDto): string {
    const protocol = config.enableHttps ? 'https' : 'http';
    
    return `// next.config.js CDN configuration
/** @type {import('next').NextConfig} */
const nextConfig = {
  // CDN for static assets
  assetPrefix: process.env.NODE_ENV === 'production' 
    ? '${protocol}://${config.domain}' 
    : undefined,
  
  // Image optimization with CDN
  images: {
    loader: 'custom',
    loaderFile: './lib/cdn-image-loader.js',
    domains: ['${config.domain}', '${config.originDomain}'],
  },
};

module.exports = nextConfig;

// lib/cdn-image-loader.js
// export default function cdnImageLoader({ src, width, quality }) {
//   return \`${protocol}://${config.domain}\${src}?w=\${width}&q=\${quality || 75}\`;
// }
`;
  }

  // 生成环境变量配置
  generateEnvConfig(config: CDNConfigDto): string {
    const protocol = config.enableHttps ? 'https' : 'http';
    
    return `# CDN Configuration
CDN_PROVIDER=${config.provider}
CDN_DOMAIN=${config.domain}
CDN_BASE_URL=${protocol}://${config.domain}
CDN_ORIGIN_DOMAIN=${config.originDomain}
CDN_ENABLE_HTTPS=${config.enableHttps ? 'true' : 'false'}
`;
  }
}
