/**
 * NestJS 模块常量
 */

export const CONFIG_MANAGER = 'CONFIG_MANAGER';
export const DICTIONARY_MANAGER = 'DICTIONARY_MANAGER';
export const CONFIG_REPOSITORY = 'CONFIG_REPOSITORY';
export const DICTIONARY_REPOSITORY = 'DICTIONARY_REPOSITORY';
export const CACHE_STRATEGY = 'CACHE_STRATEGY';
export const CONFIG_MODULE_OPTIONS = 'CONFIG_MODULE_OPTIONS';
